export type Season = "Kharif" | "Rabi" | "Zaid" | "Perennial";

export interface SeasonalCrop {
  name: string;
  displayName: string;
  emoji: string;
  season: Season;
  sowingMonths: number[];   // 1-12
  harvestMonths: number[];  // 1-12
  regions: string[];
  soilType: string;
  waterRequirement: "Low" | "Moderate" | "High";
  tips: string[];
  durationDays: string;
}

export const SEASONAL_CROPS: SeasonalCrop[] = [
  {
    name: "maize",
    displayName: "Maize",
    emoji: "🌽",
    season: "Kharif",
    sowingMonths: [6, 7],
    harvestMonths: [9, 10],
    regions: ["Karnataka", "Andhra Pradesh", "Madhya Pradesh", "Rajasthan", "Uttar Pradesh"],
    soilType: "Well-drained loamy soil",
    waterRequirement: "Moderate",
    durationDays: "90–120 days",
    tips: [
      "Sow at onset of monsoon for best germination",
      "Maintain 60–75 cm row spacing for optimal yield",
      "Apply nitrogen in split doses: basal + 30 DAS + 60 DAS",
      "Avoid waterlogging — maize is sensitive to excess moisture",
    ],
  },
  {
    name: "rice",
    displayName: "Rice",
    emoji: "🌾",
    season: "Kharif",
    sowingMonths: [6, 7, 8],
    harvestMonths: [10, 11, 12],
    regions: ["West Bengal", "Uttar Pradesh", "Andhra Pradesh", "Punjab", "Tamil Nadu"],
    soilType: "Clay loam / paddy soil with good water retention",
    waterRequirement: "High",
    durationDays: "110–150 days",
    tips: [
      "Transplant 25–30 day old seedlings to main field",
      "Maintain 2–5 cm standing water during vegetative stage",
      "Apply zinc sulfate to prevent zinc deficiency",
      "Drain field 10 days before harvest for easy mechanization",
    ],
  },
  {
    name: "cotton",
    displayName: "Cotton",
    emoji: "🌿",
    season: "Kharif",
    sowingMonths: [5, 6, 7],
    harvestMonths: [10, 11, 12],
    regions: ["Gujarat", "Maharashtra", "Telangana", "Punjab", "Haryana"],
    soilType: "Black cotton (vertisol) or deep sandy loam",
    waterRequirement: "Moderate",
    durationDays: "150–180 days",
    tips: [
      "Prefer Bt cotton hybrids for bollworm resistance",
      "Space plants 90×45 cm for optimal canopy development",
      "Irrigate at boll formation stage — critical water need",
      "Pink bollworm monitoring essential from 60 DAS onwards",
    ],
  },
  {
    name: "jute",
    displayName: "Jute",
    emoji: "🌱",
    season: "Kharif",
    sowingMonths: [3, 4, 5],
    harvestMonths: [7, 8, 9],
    regions: ["West Bengal", "Bihar", "Assam", "Odisha", "Meghalaya"],
    soilType: "Alluvial loamy soil with good drainage",
    waterRequirement: "High",
    durationDays: "120–150 days",
    tips: [
      "Sow before pre-monsoon showers for best stand",
      "Retting (water soaking) for 20–30 days releases fiber",
      "Harvest at 50% flowering stage for best fiber quality",
      "Green jute leaves are excellent organic manure",
    ],
  },
  {
    name: "banana",
    displayName: "Banana",
    emoji: "🍌",
    season: "Perennial",
    sowingMonths: [6, 7, 2, 3],
    harvestMonths: [3, 4, 5, 9, 10],
    regions: ["Tamil Nadu", "Maharashtra", "Gujarat", "Andhra Pradesh", "Karnataka"],
    soilType: "Deep, well-drained loamy soil rich in organic matter",
    waterRequirement: "High",
    durationDays: "10–14 months to first harvest",
    tips: [
      "Plant tissue culture suckers for disease-free crop",
      "Bunch covering with blue polythene improves quality",
      "Earthing up prevents lodging during heavy rains",
      "Drip irrigation saves 40–50% water over flood irrigation",
    ],
  },
  {
    name: "mango",
    displayName: "Mango",
    emoji: "🥭",
    season: "Perennial",
    sowingMonths: [7, 8],
    harvestMonths: [4, 5, 6],
    regions: ["Uttar Pradesh", "Andhra Pradesh", "Karnataka", "Bihar", "Gujarat"],
    soilType: "Deep, well-drained alluvial or laterite soil",
    waterRequirement: "Low",
    durationDays: "3–4 years to first bearing",
    tips: [
      "Graft Alphonso or Dasheri varieties for premium quality",
      "Mango needs a dry, cool winter to initiate flowering",
      "Spray KNO₃ (potassium nitrate) to induce uniform flowering",
      "Bagging of fruits prevents mango fruit fly damage",
    ],
  },
  {
    name: "coconut",
    displayName: "Coconut",
    emoji: "🥥",
    season: "Perennial",
    sowingMonths: [4, 5, 6],
    harvestMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    regions: ["Kerala", "Karnataka", "Tamil Nadu", "Andhra Pradesh", "Odisha"],
    soilType: "Sandy loam, laterite, or alluvial with high water table",
    waterRequirement: "Moderate",
    durationDays: "6–7 years to bearing; harvested year-round",
    tips: [
      "Select tall × dwarf hybrid seedlings for higher yield",
      "Intercrop with cocoa or black pepper in early years",
      "Apply salt (NaCl) 2 kg/tree/year in deficient soils",
      "Regular de-weeding in basins prevents pest build-up",
    ],
  },
  {
    name: "chickpea",
    displayName: "Chickpea",
    emoji: "🫘",
    season: "Rabi",
    sowingMonths: [10, 11],
    harvestMonths: [2, 3, 4],
    regions: ["Madhya Pradesh", "Rajasthan", "Maharashtra", "Uttar Pradesh", "Andhra Pradesh"],
    soilType: "Sandy loam to clay loam, slightly alkaline preferred",
    waterRequirement: "Low",
    durationDays: "90–110 days",
    tips: [
      "Treat seeds with Rhizobium culture for nitrogen fixation",
      "Avoid excess irrigation — chickpea is drought tolerant",
      "One pre-sowing irrigation is sufficient in dryland areas",
      "Pod borer (Helicoverpa) is major pest — monitor regularly",
    ],
  },
  {
    name: "lentil",
    displayName: "Lentil",
    emoji: "🫘",
    season: "Rabi",
    sowingMonths: [10, 11],
    harvestMonths: [2, 3, 4],
    regions: ["Madhya Pradesh", "Uttar Pradesh", "Bihar", "West Bengal", "Rajasthan"],
    soilType: "Sandy loam to loam soil, well-drained and slightly acidic",
    waterRequirement: "Low",
    durationDays: "95–120 days",
    tips: [
      "Seed treatment with Rhizobium + Trichoderma is essential",
      "Pre-sowing seed soaking for 12 hours improves germination",
      "Wilt (Fusarium) is major disease — use resistant varieties",
      "Harvest when 70–80% pods turn straw-colored",
    ],
  },
  {
    name: "pigeonpeas",
    displayName: "Pigeon Peas",
    emoji: "🫛",
    season: "Kharif",
    sowingMonths: [6, 7],
    harvestMonths: [12, 1, 2],
    regions: ["Maharashtra", "Karnataka", "Andhra Pradesh", "Madhya Pradesh", "Uttar Pradesh"],
    soilType: "Light to medium loamy soils, well-drained",
    waterRequirement: "Low",
    durationDays: "120–270 days depending on variety",
    tips: [
      "Short-duration varieties (ICPL 87) fit better in rotations",
      "Intercrop with sorghum or cotton in 1:2 row ratio",
      "Sterility mosaic disease spread by mites — spray miticides",
      "Harvest pods in 2–3 pickings for fresh vegetable use",
    ],
  },
  {
    name: "mothbeans",
    displayName: "Moth Beans",
    emoji: "🫘",
    season: "Kharif",
    sowingMonths: [7, 8],
    harvestMonths: [9, 10, 11],
    regions: ["Rajasthan", "Gujarat", "Haryana", "Maharashtra", "Uttar Pradesh"],
    soilType: "Sandy or sandy loam soil, arid zones",
    waterRequirement: "Low",
    durationDays: "60–90 days",
    tips: [
      "Ideal for arid and semi-arid regions with low rainfall",
      "Broadcast sowing @ 8–10 kg seed/ha in sandy soils",
      "Tolerates both drought and light waterlogging",
      "Excellent fodder crop; leaves enrich soil nitrogen",
    ],
  },
  {
    name: "coffee",
    displayName: "Coffee",
    emoji: "☕",
    season: "Perennial",
    sowingMonths: [5, 6],
    harvestMonths: [11, 12, 1],
    regions: ["Karnataka", "Kerala", "Tamil Nadu", "Andhra Pradesh"],
    soilType: "Deep, well-drained laterite or loamy soil, hilly terrain",
    waterRequirement: "Moderate",
    durationDays: "3–4 years to first bearing",
    tips: [
      "Shade trees (silver oak) essential for quality beans",
      "Blossom showers in Feb–March trigger flowering",
      "Arabica suited for >1000m altitude; Robusta for lower",
      "Harvest only ripe red cherries for premium quality",
    ],
  },
  {
    name: "orange",
    displayName: "Orange",
    emoji: "🍊",
    season: "Rabi",
    sowingMonths: [7, 8, 2, 3],
    harvestMonths: [11, 12, 1, 2],
    regions: ["Maharashtra (Nagpur)", "Madhya Pradesh", "Rajasthan", "Punjab", "Himachal Pradesh"],
    soilType: "Deep, well-drained sandy loam or clay loam",
    waterRequirement: "Moderate",
    durationDays: "7–8 months from flowering to harvest",
    tips: [
      "Nagpur mandarin is world-famous — maintain strict spacing",
      "Gummosis (Phytophthora) prevented by soil drenching",
      "Drip irrigation reduces water usage by 35–40%",
      "Cold storage at 5–8°C extends shelf life to 6–8 weeks",
    ],
  },
  {
    name: "papaya",
    displayName: "Papaya",
    emoji: "🍑",
    season: "Zaid",
    sowingMonths: [2, 3, 6, 7],
    harvestMonths: [9, 10, 11, 1, 2],
    regions: ["Andhra Pradesh", "Gujarat", "West Bengal", "Karnataka", "Odisha"],
    soilType: "Well-drained sandy loam or loamy soil, slightly acidic",
    waterRequirement: "Moderate",
    durationDays: "9–12 months to first harvest",
    tips: [
      "Prefer dioecious Pusa Delicious or Solo varieties",
      "Papaya ring spot virus is biggest threat — remove infected plants",
      "Does not tolerate waterlogging — raised bed cultivation recommended",
      "Apply mulch to conserve moisture and suppress weeds",
    ],
  },
  {
    name: "watermelon",
    displayName: "Watermelon",
    emoji: "🍉",
    season: "Zaid",
    sowingMonths: [2, 3, 4],
    harvestMonths: [5, 6, 7],
    regions: ["Uttar Pradesh", "Andhra Pradesh", "Karnataka", "Tamil Nadu", "Rajasthan"],
    soilType: "Sandy loam or light sandy soil with good drainage",
    waterRequirement: "Moderate",
    durationDays: "70–100 days",
    tips: [
      "River bed cultivation on sandy soil produces excellent quality",
      "Drip fertigation with NPK improves fruit weight significantly",
      "Use trellises for small vine varieties to save space",
      "Thumping test: hollow sound indicates ripeness",
    ],
  },
  {
    name: "muskmelon",
    displayName: "Muskmelon",
    emoji: "🍈",
    season: "Zaid",
    sowingMonths: [2, 3, 4],
    harvestMonths: [5, 6, 7],
    regions: ["Uttar Pradesh", "Punjab", "Rajasthan", "Madhya Pradesh", "Haryana"],
    soilType: "Light sandy loam or alluvial soil, slightly alkaline",
    waterRequirement: "Moderate",
    durationDays: "80–110 days",
    tips: [
      "Withhold irrigation 10–15 days before harvest for sweetness",
      "Hand pollination in early morning improves fruit set",
      "Powdery mildew major disease — spray wettable sulfur",
      "Apply gypsum @ 100 kg/ha for calcium supplementation",
    ],
  },
];

export const SEASON_META: Record<Season, { label: string; color: string; bg: string; border: string; months: string; desc: string }> = {
  Kharif: {
    label: "Kharif (Monsoon)",
    color: "text-blue-700",
    bg: "bg-blue-50",
    border: "border-blue-200",
    months: "Jun – Nov",
    desc: "Sown at the start of monsoon (June–July), harvested in autumn (Oct–Nov)",
  },
  Rabi: {
    label: "Rabi (Winter)",
    color: "text-amber-700",
    bg: "bg-amber-50",
    border: "border-amber-200",
    months: "Oct – Apr",
    desc: "Sown in winter (Oct–Nov), harvested in spring (Mar–Apr)",
  },
  Zaid: {
    label: "Zaid (Summer)",
    color: "text-orange-700",
    bg: "bg-orange-50",
    border: "border-orange-200",
    months: "Feb – Jul",
    desc: "Short-duration summer crops grown between Rabi and Kharif",
  },
  Perennial: {
    label: "Perennial / Year-round",
    color: "text-brand-700",
    bg: "bg-brand-50",
    border: "border-brand-200",
    months: "Year-round",
    desc: "Permanent crops that produce over multiple years",
  },
};

export const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
